# Generated by Django 2.1.2 on 2019-01-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user_house_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Alex', max_length=50),
            preserve_default=False,
        ),
    ]
