# Generated by Django 2.1.2 on 2019-02-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_cctv_room_roomproperty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='no_of_room',
        ),
    ]
