# Generated by Django 2.1.2 on 2018-12-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30)),
                ('eage', models.IntegerField()),
                ('ecity', models.CharField(max_length=30)),
                ('edsg', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
