# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.FileField(null=True, upload_to='pic'),
        ),
    ]
