# Generated by Django 2.1.4 on 2019-02-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restromenudb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=30)),
                ('Item_Type', models.CharField(choices=[('DRY', 'Dry'), ('GRAVY', 'Gravy')], max_length=5)),
                ('Image', models.ImageField(upload_to='Item_images')),
            ],
        ),
    ]
