# Generated by Django 2.1.4 on 2018-12-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181219_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='/static/img/default.png', null=True, upload_to='user'),
        ),
    ]
