# Generated by Django 2.1.4 on 2018-12-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181219_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='/home/shubham/Downloads/abc.png', null=True, upload_to='user'),
        ),
    ]
