# Generated by Django 2.1.3 on 2019-02-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proff_name',
            old_name='Proff_name',
            new_name='Proff',
        ),
        migrations.AddField(
            model_name='proff_name',
            name='proff_name',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
