# Generated by Django 2.1.3 on 2019-02-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190212_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
