# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-25 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20161225_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
    ]
