# Generated by Django 2.1.4 on 2018-12-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181220_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='real_estate/static/img/default.png', null=True, upload_to='user'),
        ),
    ]
