# Generated by Django 2.1.3 on 2019-02-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddharForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=30)),
                ('Parents_name', models.CharField(max_length=20)),
                ('Mob_no', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
