# Generated by Django 2.1.2 on 2019-01-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='house_name',
            field=models.CharField(default='Shanti Villa', max_length=50),
            preserve_default=False,
        ),
    ]
